app = "ecoprimers"
primary_region = "sin"

[env]
FLASK_APP = "src/main.py"
FLASK_DEBUG = "0"

[http_service]
internal_port = 5000
force_https = true
auto_start_machines = true
auto_stop_machines = "stop"
min_machines_running = 0
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024