"""empty message

Revision ID: d4db3833ac20
Revises: 
Create Date: 2025-01-08 11:19:27.876828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4db3833ac20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('date', sa.String(), nullable=False))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('birthday', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('birthday')
        batch_op.drop_column('bio')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('date')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
