name: Web Deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}
jobs:
  deploy:
    name: Deploy
    environment: Production
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Setup uv
        uses: astral-sh/setup-uv@v7

      - name: Install Dependencies
        run: |
          bun install --frozen-lockfile
          uv sync --frozen --no-dev

      - name: Migrate Database
        run: make migrate

      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v4
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          secrets: |
            DATABASE_URL
            SECRET_KEY
            GOOGLE_CLIENT_ID
            GOOGLE_CLIENT_SECRET
            TURNSTILE_SITE_KEY
            TURNSTILE_SECRET_KEY
            OPENROUTER_API_KEY
            OPENROUTER_TITLE
            OPENROUTER_REFERER
            OPENROUTER_MODEL
            RESEND_API_KEY
            RESEND_FROM_NAME
            RESEND_FROM_EMAIL
            OPENWEATHER_API_KEY
            NEWS_API_KEY
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          TURNSTILE_SITE_KEY: ${{ secrets.TURNSTILE_SITE_KEY }}
          TURNSTILE_SECRET_KEY: ${{ secrets.TURNSTILE_SECRET_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          OPENROUTER_TITLE: ${{ vars.OPENROUTER_TITLE }}
          OPENROUTER_REFERER: ${{ vars.OPENROUTER_REFERER }}
          OPENROUTER_MODEL: ${{ vars.OPENROUTER_MODEL }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          RESEND_FROM_NAME: ${{ vars.RESEND_FROM_NAME }}
          RESEND_FROM_EMAIL: ${{ vars.RESEND_FROM_EMAIL }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
