name: Web Deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  deploy:
    name: Deploy
    environment: Production
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Upload Secrets
        run: |
          flyctl secrets set \
            SECRET_KEY="${{ secrets.SECRET_KEY }}" \
            DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            STRIPE_SECRET_KEY="${{ secrets.STRIPE_SECRET_KEY }}" \
            STRIPE_PUBLIC_KEY="${{ secrets.STRIPE_PUBLIC_KEY }}" \
            GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
            GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
            GOOGLE_RECAPTCHA_SITE_KEY="${{ secrets.GOOGLE_RECAPTCHA_SITE_KEY }}" \
            GOOGLE_RECAPTCHA_SECRET_KEY="${{ secrets.GOOGLE_RECAPTCHA_SECRET_KEY }}" \
            OPENROUTER_API_KEY="${{ secrets.OPENROUTER_API_KEY }}" \
            OPENROUTER_TITLE="${{ vars.OPENROUTER_TITLE }}" \
            OPENROUTER_REFERER="${{ vars.OPENROUTER_REFERER }}" \
            OPENROUTER_MODEL="${{ vars.OPENROUTER_MODEL }}" \
            RESEND_API_KEY="${{ secrets.RESEND_API_KEY }}" \
            RESEND_FROM_EMAIL="${{ vars.RESEND_FROM_EMAIL }}" \
            OPENWEATHER_API_KEY="${{ secrets.OPENWEATHER_API_KEY }}"

      - name: Deploy to Fly
        run: flyctl deploy
